using System;

public enum SIUpgradeType
{
	Initialize = -1,
	Thruster_Unlock,
	Thruster_Jet,
	Thruster_Prop,
	Thruster_Jet_Duration,
	Thruster_Jet_Accel,
	Thruster_Prop_Duration,
	Thruster_Prop_Speed,
	Thruster_Jet_Tag,
	Thruster_Prop_Knockback,
	Thruster_Fuel_Grounding,
	Thruster_Throttle_Control,
	Stilt_Unlock = 100,
	Stilt_Tag_Tip,
	Stilt_Retractable,
	Stilt_Adjustable_Length,
	Stilt_Retract_Speed,
	Stilt_Max_Length,
	Stilt_Stun_Tip,
	Stilt_Muscle_Fusion,
	Stilt_Short,
	Stilt_Long,
	Grenade_Concussion_Unlock = 200,
	Grenade_Antigravity_Unlock,
	Grenade_Concussion_Stun,
	Grenade_Concussion_Radius,
	Grenade_Antigravity_Persists,
	Grenade_Antigravity_Cooldown,
	Grenade_Concussion_Self_Boost,
	Grenade_Concussion_Overcharge,
	Grenade_Antigravity_Pro_Gravity,
	Grenade_Concussion_Impact_Accelerant,
	Grenade_Antigravity_Gravity_Bomb,
	Grenade_Antigravity_Black_Hole,
	Grenade_Holster_Unlock,
	Grenade_Stun_Unlock,
	Grenade_Puller_Unlock,
	Grenade_Disrupter_Unlock,
	Dash_Warpprism_Unlock = 300,
	Dash_Yoyo_Unlock,
	Dash_Warpprism_Range,
	Dash_Warpprism_Cooldown,
	Dash_Yoyo_Range,
	Dash_Yoyo_Speed,
	Dash_Warpprism_Intangible,
	Dash_Warpprism_Shake,
	Dash_Yoyo_Cooldown,
	Dash_Yoyo_Dynamic,
	Dash_Warpprism_Swap_Positions,
	Dash_Yoyo_Stun,
	Dash_Yoyo_Tag,
	Dash_Yoyo_Teleport,
	Platform_Unlock = 400,
	Platform_Cooldown,
	Platform_Duration,
	Platform_Capacity,
	Platform_SpeedBoost,
	Tapteleport_Unlock = 500,
	Tapteleport_Zone,
	Tapteleport_Stealth,
	Tapteleport_Portal_Selection,
	Tapteleport_Keep_Velocity,
	Tapteleport_Infinite_Use
}
